
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Dec 17 19:50:05 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int SEMICOLON = 7;
  public static final int ELSE = 16;
  public static final int OR = 17;
  public static final int GREATER_OR_EQUAL_TO = 24;
  public static final int CHAR = 11;
  public static final int WHILE = 15;
  public static final int END = 5;
  public static final int GREATER = 23;
  public static final int COLON = 6;
  public static final int ID = 9;
  public static final int PROGRAM = 2;
  public static final int OPEN_BRACKET = 25;
  public static final int EQUAL_TO = 21;
  public static final int NOT_EQUAL_TO = 22;
  public static final int BEGIN = 4;
  public static final int LESS_OR_EQUAL_TO = 20;
  public static final int BOOLEAN = 13;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CONST = 27;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ASSIGN = 14;
  public static final int CLOSED_BRACKET = 26;
  public static final int INTEGER = 10;
  public static final int REAL = 12;
  public static final int LESS = 19;
}

