
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 30 10:21:11 CET 2021
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 17;
  public static final int SEMICOLON = 7;
  public static final int ELSE = 15;
  public static final int OR = 16;
  public static final int INTEGERCONST = 27;
  public static final int GREATER_OR_EQUAL_TO = 23;
  public static final int CHAR = 10;
  public static final int WHILE = 14;
  public static final int BOOLEANCONST = 29;
  public static final int END = 5;
  public static final int GREATER = 22;
  public static final int COLON = 6;
  public static final int ID = 26;
  public static final int PROGRAM = 2;
  public static final int OPEN_BRACKET = 24;
  public static final int EQUAL_TO = 20;
  public static final int NOT_EQUAL_TO = 21;
  public static final int BEGIN = 4;
  public static final int LESS_OR_EQUAL_TO = 19;
  public static final int BOOLEAN = 12;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int CHARCONST = 30;
  public static final int REALCONST = 28;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int ASSIGN = 13;
  public static final int CLOSED_BRACKET = 25;
  public static final int INTEGER = 9;
  public static final int REAL = 11;
  public static final int LESS = 18;
}

